### ISSUE TITLE
Not minifying anymore

### ISSUE THREAD

**Issue by maxresnikoff** [Josee9988/MinifyAll#102]
Won't minify anything anymore. Usually have it to minify to a new .min file on save, but not working.
Also right-clicking and manually minifying and preserving original no longer works. 
Have re-installed the extension but no luck.

**Comment by Josee9988** [comment]
What are your extension settings?

**Comment by maxresnikoff** [comment]
I Have reverted to 2.5.12 and works fine again. 

Here are my settings: 
"MinifyAll.disableHtml": true,
    "MinifyAll.disableJson": true,
    "MinifyAll.disableJsonc": true,
    "MinifyAll.disableLess": true,
    "MinifyAll.disablePhp": true,
    "MinifyAll.disableSass": true,
    "MinifyAll.disableScss": true,
    "MinifyAll.PrefixOfNewMinifiedFiles": ".min",
    "MinifyAll.openMinifiedDocument": false,
    "MinifyAll.minifyOnSaveToNewFile": true,
    "MinifyAll.minifyOnSave": true,
    "MinifyAll.terserMinifyOptions": {

**Comment by Josee9988** [comment]
If you switch back to 2.5.20 will it minify again or give any output error?
Does any of all the commands work?

**Comment by maxresnikoff** [comment]
So i reverted back to 2.5.13 and that didn't work either. Nothing was minifying at all
Reverted again back to 2.5.12 and all working perfectly. 

On v2.5.13 & 2.5.14, no error messages were shown. It just wouldn't minify.

For me: 
V2.5.12 - Works
V2.5.13 - Doesn't work
V2.5.14 - Doesn't work

**Comment by Josee9988** [comment]
What about the latest version v2.5.20?

**Comment by Josee9988** [comment]
The latest version is 2.5.20
you can check it here: https://marketplace.visualstudio.com/items?itemName=josee9988.minifyall

**Comment by maxresnikoff** [comment]
Very odd, as VS shows the latest as 2.5.14 and there is no newer version to install... 
![Screenshot 2021-04-13 at 10 53 23](https://user-images.githubusercontent.com/48560713/114534114-8c466700-9c46-11eb-9473-1c42f4df73da.png)

**Comment by maxresnikoff** [comment]
I can confirm it is working. Many apologies! my mistake with VScode not updating and hence not being compatible with v2.5.20

**Comment by Josee9988** [comment]
Always stay up to date! 😄
