### ISSUE TITLE
[Bug] Minificar HTML con IF PHP

### ISSUE THREAD

**Issue by AndyGotfridt** [Josee9988/MinifyAll#105]
# **🐞 Bug Report**

## **Describe the bug**
* Al minificar un HTML que contiene un IF de PHP borra los ; de los echo o variables (No sucede en todos los casos, como se aprecia en la captura)

---

### **Is this a regression?**
* No lo probé en versiones anteriores, ya que es la primera vez que utilizo la extensión

---

### **To Reproduce**

1. En un archivo html generar un IF (PHP)
2. Minificar el archivo (Desde menú o automáticamente al guardar)
3. Revisar el archivo minificado

---

### **Expected behaviour**

* Se espera el siguiente if:
`<?php if($algo==true){echo"hola";}else{echo"chau";}?>`

---

### **Media prove**

HTML SIN MINIFICAR

![SIN MINIFICAR](https://i.imgur.com/wqK4d4I.png)

HTML MINIFICADO

![MINIFICADO](https://i.imgur.com/3ll72DG.png)

---

### **Your environment**

* OS: MacOs Big Sur 11.3
* Node version: 14.16.1
* Npm version: 6.14.12
* Browser name and version: Google Chrome v. 90.0.4430.93

---

**Comment by Josee9988** [comment]
Hola @AndyGotfridt
Actualmente la extensión no soporta la minimización de archivos enteros con código PHP, es algo que definitivamente me gustaría añadir, pero no tengo tiempo de momento.

Puedes minimizar simplemente el html seleccionandolo y usando el comando "Minify the selected text"

Gracias y disculpa la inconveniencia

**Comment by Josee9988** [comment]
El proyecto es un side project y por ahora no puedo dedicarle el tiempo que me gustaría s desarrollar las features que me comentáis ya que la universidad consume gran parte de mi tiempo, pero intentaré sacar horas en verano.
Gracias por tu comprensión @AndyGotfridt !!
