### ISSUE TITLE
Autosave original and minified

### ISSUE THREAD

**Issue by samprorender** [Josee9988/MinifyAll#106]
I would like to use CTR+S to save the original file and the minified file at the same time. That way I can link the CSS-min directly into the HTML and not have to transform each time.
I haven't found a way to do this.

Thanks

**Comment by Josee9988** [comment]
Ok, I think you are looking for this setting:
"MinifyAll.minifyOnSaveToNewFile​"​: ​true
And set 
"MinifyAll.minifyOnSave": false

Remember to restart VSCode to apply the settings.

Tell me if that is what you were looking for

Thanks for contributing!

**Comment by samprorender** [comment]
It worked for me. For some reason it didn't work before. Sorry
Thanks, excellent plugin.
