### ISSUE TITLE
Gzip minified files

### ISSUE THREAD

**Issue by mojtabakaviani** [Josee9988/MinifyAll#107]
Thanks for developed this extension, please add option to gzip after minified files.

**Comment by Josee9988** [comment]
That is a good feature, I'll try to implement this in the future.
For now my time is extremely limited. Thanks for the idea

**Comment by Josee9988** [comment]
I will try to do it as soon as I finish my university exams, probably in June, I know it is a lot of time but for now, I don't feel ready to spend more time on my foss projects.

Sorry for the delay @mojtabakaviani , but I will solve this issue sooner or later!

**Comment by Josee9988** [comment]
Hey @mojtabakaviani I've already implemented it in a dev branch.
I will publish it in the upcoming days, sorry for the delay :D

**Comment by Josee9988** [comment]
I've made it to compress files and folders, as I said it will be available soon ;)

**Comment by Josee9988** [comment]
Download the latest version 2.6.0 so you can check the new feature. Please tell me how it was and if I could improve something about it.
Thanks
