### ISSUE TITLE
example html minified but with multiple lines

### ISSUE THREAD

**Issue by davidpetrey** [Josee9988/MinifyAll#11]
For some reason my code isn't show correctly here in github. 

I've disabled all of my other plugins.

Example html:
```<!DOCTYPE html>
<html lang="es">

<head>
    <title></title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="">
    <script type="text/javascript' src=""></script>
    <!-- test -->
</head>

<!-- ~~~~~✦✦✦✦✦ B O
 D Y ✦✦✦✦✦~~~~~ -->
<body>
    
</body>

</html>


Minified html:
<!DOCTYPE html>
<html lang="es"><head> <title></title> <meta charset="utf-8"> <link rel="stylesheet"href=""> <script type="text/javascript' src=""></script> </head>
<body></body></html>

**Comment by davidpetrey** [comment]
I could not get the code to show properly with the back ticks but now it's displaying the way I'm seeing it.

**Comment by davidpetrey** [comment]
![image](https://user-images.githubusercontent.com/13895170/70928319-654a3780-1ff6-11ea-8932-e7706fcff8d8.png)

**Comment by Josee9988** [comment]
Hi, @davidpetrey I can not understand what is happening or what are you doing.

The code: 
```html
<html lang="es">

<head>
    <title></title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="">
    <script type="text/javascript' src=""></script>
    <!-- test -->
</head>

<!-- ~~~~~✦✦✦✦✦ B O
 D Y ✦✦✦✦✦~~~~~ -->
<body>
    
</body>

</html>
```

Is giving me the output:
```html
<html lang="es"><head><title></title><meta charset="utf-8"><link rel="stylesheet"href=""><script type="text/javascript' src=""></script></head><body></body></html>
```

With all the commands. And the expected code is in just one line.
Maybe you could tell us what command are you using or what is happening because I've used all the commands from the extension and all are giving me the expected output, maybe I'm missing something.

**Comment by davidpetrey** [comment]
I was just doing "Minify this document and preserve the original" command.  I get same results with "Minify this document".     

It's ok. I figured out that I can just Find & Replace new lines to remove them and I get one line of code. That's all I needed.    I must have a setting or something causing the issue.  Thanks anyways.

**Comment by Josee9988** [comment]
> I was just doing "Minify this document and preserve the original" command. I get same results with "Minify this document".
> 
> It's ok. I figured out that I can just Find & Replace new lines to remove them and I get one line of code. That's all I needed. I must have a setting or something causing the issue. Thanks anyways.

I have just checked it again with both of the commands you addressed, and I got all the code in one line and perfectly minified. Maybe you have a setting that is splitting the text or something.

Anyways, thanks for trying to improve the extension, your intention is highly appreciated :100: 
Thanks @davidpetrey
