### ISSUE TITLE
XML Minify

### ISSUE THREAD

**Issue by Runeloon** [Josee9988/MinifyAll#119]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**
Dealing with large XML blobs that I'm inserting into SQL statements, prefer to keep to a single line so they don't distract from the rest of my code. Have been using this tool for JSON blobs and it's worked perfectly.

*

---

## **Describe the solution you'd like**
Noticed switching the language mode to HTML and then minifying appeared to work perfectly. Hopefully that means you can copy whatever logic is being used with little difficulty?

---

## **Describe alternatives you've considered**
There are online XML minifyers, but that is subject to copy-paste limits, and I'd just prefer my editor be able to do it.

---

**Comment by Josee9988** [comment]
Hi, so does the minifier minify your XML code right when using it as HTML?

Because I could just add XML as an HTML minimisation

**Comment by Runeloon** [comment]
After a bit of further testing, I think the HTML minifier will work perfectly for the XML.
I will note that CDATA blocks get a bit screwed up, with some newlines being removed, while others aren't. CDATA is an odd exception, as it can kind of contain _anything_, and maybe shouldn't be minified at all. This won't impact me since none of the XML I'll be using uses CDATA.

**Comment by Josee9988** [comment]
You can now download the latest minifyall version (2.9.0) and check if it works for you ;))

**Comment by Runeloon** [comment]
Downloaded, works perfectly! Thanks for the change :D
