### ISSUE TITLE
What about uglifying?

### ISSUE THREAD

**Issue by Icaras12x** [Josee9988/MinifyAll#12]
Could you implement an option to uglify js?

**Comment by Josee9988** [comment]
@Icaras12x is terser not working ok?

**Comment by Icaras12x** [comment]
Hello Jose,
js is minifying the project correctly, what I meant was probably mangling ? I mean the file should change all the name variables. Let me know about this and if it works how to enable this. Cheers

________________________________
Da: Jose Gracia Berenguer <notifications@github.com>
Inviato: venerdì 20 dicembre 2019 16:52
A: Josee9988/MinifyAll <MinifyAll@noreply.github.com>
Cc: Icaras12x <ale12manto@live.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [Josee9988/MinifyAll] What about uglifying? (#12)


@Icaras12x<https://github.com/Icaras12x> is terser not working ok?

**Comment by Josee9988** [comment]
@Icaras12x I didn't test terser a lot but I'll take a look about what you are saying, if you could give me some piece of code that demonstrate what you say that could be helpful to test uglify aswell

**Comment by Icaras12x** [comment]
I don't know what's going on but when I minify I get some errors.
Thanks for your patience.

________________________________
Da: Jose Gracia Berenguer <notifications@github.com>
Inviato: venerdì 20 dicembre 2019 21:57
A: Josee9988/MinifyAll <MinifyAll@noreply.github.com>
Cc: Icaras12x <ale12manto@live.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [Josee9988/MinifyAll] What about uglifying? (#12)


@Icaras12x<https://github.com/Icaras12x> I didn't test terser a lot but I'll take a look about what you are saying, if you could give me some piece of code that demonstrate what you say that could be helpful to test uglify aswell

**Comment by Josee9988** [comment]
@Icaras12x in JavaScript? Address the code so I can test it

**Comment by Icaras12x** [comment]
Yep it's js

________________________________
Da: Jose Gracia Berenguer <notifications@github.com>
Inviato: sabato 21 dicembre 2019 08:25
A: Josee9988/MinifyAll <MinifyAll@noreply.github.com>
Cc: Icaras12x <ale12manto@live.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [Josee9988/MinifyAll] What about uglifying? (#12)


@Icaras12x<https://github.com/Icaras12x> in JavaScript? Address the code so I can test it

**Comment by Josee9988** [comment]
@Icaras12x Mind giving me the code that fails so I can test it?
