### ISSUE TITLE
Enhancement Request: right-click menu togglable via config?

### ISSUE THREAD

**Issue by Cube707** [Josee9988/MinifyAll#120]
# **🚀 Enhancement Request**

Hello there, really good extention. I Have a enhancement request you might consider:

I don't use the right-click menu very much with this extention and find it somewhat intrusive as well as clicking it by acident.
This isn't too bad and I could totally live with it, but I figured it might be posible to provide a toggle for it in the configs? So one could just disable it and only use the comands? I think this might be a good addition and wouldn't force anything on people who like the right-click Options.

best Regards

**Comment by Josee9988** [comment]
Hi, I could understand and I certainly agree, this could be annoying or intrusive.

There isn't a clear way to toggle that using the VSCode api, but this could be manually or fixed with an script.

I'll try to investigate a bit

Thanks

**Comment by Cube707** [comment]
I am fiddling around with it myself right now. Will come back if I find something

**Comment by Josee9988** [comment]
Install the newest version 2.8.0 to start using your new feature.

Thanks again!
