### ISSUE TITLE
Missing option: Minify All: XML

### ISSUE THREAD

**Issue by goslingcools** [Josee9988/MinifyAll#129]
# **❓ Question or Support Request**

## **Describe your question or ask for support.**

Looks like this option is missing: Minify All: **Disable XML**

Now when I save any .xml file, it gets a minified version automatically next to the original.
saving sample.xml results in the file **sample.xml** AND **sample.min.xml**
I was able to disable all other filetypes I did not want to be minified except for the xml's...

**Comment by Josee9988** [comment]
I will check it, thanks for the issue

**Comment by Cube707** [comment]
@goslingcools I opened a PR to fix this issue. If its urgend on your end you can use my fork for the time beeing or wait untill its merged.

**Comment by Josee9988** [comment]
It is now published :D
