### ISSUE TITLE
Se abre la version minimizada en la misma pestaña.

### ISSUE THREAD

**Issue by LoHacemosWeb** [Josee9988/MinifyAll#14]
A la hora de guardar un documento por ejemplo un .JS, sí que me genera la versión -min.js, pero a su vez me abre en la misma pestaña del código original la versión reducida, por lo que entiendo que se sobre escribiría el original, aparte de no poder seguir modificandolo sin cerrarlo primero.

Configuración usada:
![Sin título-1](https://user-images.githubusercontent.com/7949178/71764930-9e3b4500-2eee-11ea-8eee-8123fca5d37f.jpg)

Vista de lo que hace [https://vimeo.com/382749776](https://vimeo.com/382749776)

Un saludo y gracias.

**Comment by Josee9988** [comment]
Hola, @LoHacemosWeb se te abre la pestaña actual minifizada porque tienes la setting

``` json
    "MinifyAll.minifyOnSave": true,
```
 "MinifyAll.minifyOnSave": true: Va a minifizar tu pestaña actual. Y a parte tienes: 

``` json
    "MinifyAll.minifyOnSaveToNewFile": true,
```
La cual te minimiza el actual en un nuevo fichero.

Tu solución es poner minify on save a false.
``` json
    "MinifyAll.minifyOnSave": false,
```

**Comment by Josee9988** [comment]
No veo que nada esté mal, sino que estás utilizando una configuración de ajustes que realmente no deseas.
Si quieres que solo se te minimice cuando guardas sólo pon:
"MinifyAll.minifyOnSaveToNewFile": true,

Y si quieres que solo se te minimice cuando guardas pero en el documento actual entonces utiliza:
"MinifyAll.minifyOnSave": true,
Aunque es esta setting la que creo que no deseas utilizar.

Un saludo y gracias por intentar mejorar esta extension @LoHacemosWeb !!

**Comment by LoHacemosWeb** [comment]
Ahora si, muchas gracias :)
