### ISSUE TITLE
Agregar extensiones de archivos a omitir.

### ISSUE THREAD

**Issue by LoHacemosWeb** [Josee9988/MinifyAll#15]
La idea sería que añadieras la opción de poder agregar una lista de extensiones de archivos ya que por ejemplo he abierto un .php y al guardar me lo ha creado la versión reducida y no debería.

No se como funciona exactamente, pero la idea sería algo asi.
`MinifyAll.ignoreFileExtensions = [".php", ".ext", "etc"]`

Investigaré mas sobre el como funcionan las extensiones del VSCode para poder ayudarte a implementar alguna de estas ideas, si quisieras claro.

**Off topic:** Yo antes usaba el DreamWeaver para editar las paginas web, porque permite crear "proyectos" por separado y acceso rapido, colorea la sintaxis,  la subida mediante FTP, y alguna cosa que otra, nunca como diseñador (mete o metía mucha basura en el código almenos en 2005) junto a un programita que se llamaba Koala que me generaba los CSS a partir de SCSS y me reducía los JS, para Java usaba el NetBeans IDE y para C# uso el Visual Studio.

Y ahora estoy tratando de "amoldar" el Visual Studio Code a que me haga todo eso para las paginas web.

Insisto en el buen trabajo que estas realizando con la extensión ;)

**Comment by Josee9988** [comment]
Hola de nuevo! 
Ya hay opciones para ignorar tipos de archivos, por ejemplo la de HTML es:

```json
"MinifyAll.disableHtml": true
```

Tienes de todos los tipos de archivos disponibles menos la de PHP, la cual me acabo de dar cuenta de que no está creada, esta tarde la haré.

De todas formas tenía pensado hacer solo una setting que fuese un array con todos los tipos de archivos, pero de momento, por falta de tiempo y por cómo tengo ya estructurado el código, tengo una setting para cada lenguaje que se quiere deshabilitar.

Te recomiendo que te leas el readme.md en la parte donde pone las configuraciones, específicamente: [aqui](https://github.com/Josee9988/MinifyAll/blob/master/README.md#disabling-languages-configuration)

Con respecto al tema de que si quieres implementar algunas ideas, este proyecto lo he hecho desde 0 solo y por falta de tiempo no implemento o mejoro cosas y ayuda de la comunidad es siempre bienvenida, siempre que los cambios estén bien hechos y sean positivos.

Con respecto a tu antiguo stack de desarrollo, en cuanto te acostumbres y configures VSCode a tu gusto, vas a notar un mayor rendimiento y comodidad al desarrollar.

Muchas gracias y un saludo!!:smiley:

**Comment by LoHacemosWeb** [comment]
Para darte una pista de como implementarlo:
En el archivo **main.js** línea 31:
```
function activate(context) {
	var Excludes = exports.settings.ignoreFileExtensions;
	if (Excludes.includes(vscode.window.activeTextEditor.document.languageId) >= 1 ){
	
	}
```

**Comment by Josee9988** [comment]
Por estar, ya está implementado, y así no se va a poder hacer porque no todos los comandos reciben la extensión desde 
vscode.window.activetexteditor.....

La comprobación se realiza en el archivo checkLanguage.ts el cual se llama cada vez que se va a ejecutar un comando dentro de su propio switch case, porque, como ya te he comentado no siempre se recibe igual en cada comando y no siempre se siguen los mismos pasos de manera exacta.

De todas maneras no tengo problema en convertir cada setting individual a un array, no es algo que no sepa cómo hacer, sino que se hará cuando me sobre el tiempo y le pueda dedicar a este proyecto, aunque siempre se puede hacer por la comunidad por los pull requests.

**Comment by Josee9988** [comment]
Hola @LoHacemosWeb , en la nueva versión 2.1.0 ya tienes disponible la configuración para deshabilitar PHP.
```json
    "MinifyAll.disablePhp": true
```
