### ISSUE TITLE
Problem with "Minify this document and preserve the original"

### ISSUE THREAD

**Issue by MatuxCba** [Josee9988/MinifyAll#17]
I have problems using this "Minify this document and preserve the original" function.
My projects are in the drive D: \
The extension tries to save the new file in the C: \ drive

1. select the file in my work area
2. Right click on this
3. I select the option "Minify this document and keep the original"
4. I see the following error: Error: ENOENT: no such file or directory exists, open 'C: \ d: \ Projects \ WebVeng \ css \ fontello.css'

You are using by default the drive where vscode is installed.

![image](https://user-images.githubusercontent.com/7544538/72984585-d1247a80-3dc2-11ea-844a-44a5849001d0.png)

**Comment by Josee9988** [comment]
Hola Matías, presupongo que eres español así que me ahorro el inglés:smile:.

Tu fichero me imagino que está en: D:\Projects\WebVeng\css\fontello.css , pero te añade un C:\ al principio, cierto?

En teoría no es un problema de la extensión en sí, sino del escritor de ficheros de node.

Tengo que admitir que no he probado en Windows a utilizar ese comando en un disco que no fuese el C: 

Intentaré reproducir el error y veré cuál es la manera de arreglarlo o si los de node están al tanto del problema.

Gracias por comentar!

**Comment by Josee9988** [comment]
@MatuxCba , en efecto, hay un probema en windows con ese comando, es problema del FileSaver, que de primeras está detectando mal el path de tu fichero, no funciona en ninguna unidad, ni la **C**, ni la **D**. No sé si llegaré a fixearlo ya que no poseo de un Windows con todas las herramientas de desarrollo y la mayoría de los usuarios utilizan sistemas basados en UNIX, es decir, que no sé si llegaré a arreglarlo. 

Lo voy a poner en la sección de **known bugs** y cerraré la issue, para arreglarla en un futuro.

De todas maneras, muchas gracias por comentar y intentar hacer esta extensión mejor!

**Comment by Josee9988** [comment]
It is fixed now!

**Comment by MatuxCba** [comment]
Excelente noticia!..

Buen trabajo José!..
Muchas gracias!
