### ISSUE TITLE
An issue with the minify json feature

### ISSUE THREAD

**Issue by irfantaufiq** [Josee9988/MinifyAll#18]
**The Issue**
When I use this extension to minify a json file, it won't remove space after comma in the json array.

**The Example**
For example, the current version of this extension will minify these lines:
```
{
	"Object1": ["item1", "item2", "item3"]
}
```
into `{"Object1":["item1", "item2", "item3"]}` instead of `{"Object1":["item1","item2","item3"]}`.

**The Solution**
For example, you can look at this commit: https://github.com/irfantaufiq/MinifyAll/commit/c67a763afa116ba59bf96725fa54594ff07980ea

**Comment by Josee9988** [comment]
Hey, I see the problem, I'll add your changes in a couple of hours, or if you want to could do a pull request.
Anyways thanks for posting our and letting me know of this issue, your help is highly appreciated over there. 

Thanks!!

**Comment by irfantaufiq** [comment]
Thanks for the respons.

It should be noted that my current commit is still have issue when the array item (value) isn't a string.
For example, the following lines:
```
{
	"Object1": ["item1", true, 0, "item4"]
}
```
will be minified into `{"Object1":["item1",true, 0, "item4"]}` instead of `{"Object1":["item1",true,0,"item4"]}`.

**Comment by Josee9988** [comment]
Hey @irfantaufiq , I just fixed these two issues, thanks for the help and for letting me know!!

Make sure to download the latest version from the VSCode marketplace and check the new changes.

Thanks for your help!
