### ISSUE TITLE
Error: ENOENT

### ISSUE THREAD

**Issue by kanlukasz** [Josee9988/MinifyAll#19]
**Describe the bug**
Not working if you try run minify from SideBar 

**To Reproduce**
1. Open simple folder with simple project
2. Click on this:
![obraz](https://user-images.githubusercontent.com/30685349/74086180-b6b7f580-4a80-11ea-8f60-2fea8ff8487e.png)
3. See error
![obraz](https://user-images.githubusercontent.com/30685349/74086171-a0aa3500-4a80-11ea-8386-b7e484940b53.png)

**Additional context**
1. double path on error `C:\c:\` ??
2. Everything work ok if i run minify from the Editor or from command line:

![obraz](https://user-images.githubusercontent.com/30685349/74086323-1236b300-4a82-11ea-93a9-86038b3a3889.png)

![obraz](https://user-images.githubusercontent.com/30685349/74086329-1c58b180-4a82-11ea-9215-0e3e820d48fa.png)

![obraz](https://user-images.githubusercontent.com/30685349/74086343-43af7e80-4a82-11ea-8717-c0f7bd4b3427.png)

![obraz](https://user-images.githubusercontent.com/30685349/74086329-1c58b180-4a82-11ea-9215-0e3e820d48fa.png)

**Env:**
![obraz](https://user-images.githubusercontent.com/30685349/74086552-0cda6800-4a84-11ea-85d6-eb724c64faff.png)
![obraz](https://user-images.githubusercontent.com/30685349/74086555-14017600-4a84-11ea-86e1-f82e0b56c4c0.png)

**Comment by Josee9988** [comment]
Duplicate, check issue #17 
I am sorry to hear that, I'm completely aware of this problem but for now It won't be fixed.
You have more information in the [duplicated issue](https://github.com/Josee9988/MinifyAll/issues/17)

Thank you for your time and I really appreciate your goodwill.

Thanks!!

**Comment by kanlukasz** [comment]
Thank you for the quick reply.
I'm afraid I can't check #17 because I don't speak this language
Anyway ... if you can't fix it, it might be a good idea to remove this option. To be honest, I don't think that option it's really necessary

**Comment by Josee9988** [comment]
Ow that post was in Spanish, my bad!

I just said that this problem appear only in windows devices and dome of the users are using Linux base systems, so that's the reason why I don't remove the option, because it work in Linux.

I'm so sorry for the inconveniences!

**Comment by Josee9988** [comment]
It is fixed now!
