### ISSUE TITLE
CSS minification error

### ISSUE THREAD

**Issue by marcelashun** [Josee9988/MinifyAll#20]
.mediabox-close {
  background: url(../img/**me**diabox-close.png);
}

get's minified into

.mediabox-close{background:url(../img/**m.e**diabox-close.png);}

**Comment by Josee9988** [comment]
Hey, @marcelashun it is **fixed** now.

It was a weird problem with the comment remover.

Thanks for letting me know!!

**Comment by Josee9988** [comment]
Ps: Download the next version and check it out.

**Comment by marcelashun** [comment]
Great it works now,

thx for the quick support. :)

Greets
Marcel
