### ISSUE TITLE
CSS minification issue

### ISSUE THREAD

**Issue by giuliac1989** [Josee9988/MinifyAll#22]
Hi,

I can't minify css files anymore and I can't understand why. The configuration seems correct and also the css file. I've this error: "We can not format this file type yet, use a valid one."

Thanks!

![Schermata 2020-03-10 alle 11 48 57](https://user-images.githubusercontent.com/33481534/76305434-6e7d3480-62c5-11ea-8b51-1db66f7587c7.png)

![Schermata 2020-03-10 alle 11 49 32](https://user-images.githubusercontent.com/33481534/76305463-776e0600-62c5-11ea-914d-d97a326a8c26.png)

**Comment by Josee9988** [comment]
Hi, @giuliac1989 I just tested it and it worked out perfectly, make sure the file type is set to CSS and set your MinifyAll settings to their default settings. Then tell me.

Thanks for posting out!

**Comment by Josee9988** [comment]
@giuliac1989 at the bottom right corner choose "select language mode", choose 'CSS', and then try to right-click or go to the command panel and minify the text. I really do think this is the problem.

![Screenshot from 2020-03-11 20-24-42](https://user-images.githubusercontent.com/38838976/76455852-77116000-63d6-11ea-9b25-3081ec4a17e7.png)

**Comment by giuliac1989** [comment]
Great! That's the problem!
Thank you very much :)
