### ISSUE TITLE
Conserve space after closed tag

### ISSUE THREAD

**Issue by kwizfreak** [Josee9988/MinifyAll#26]
Hi,
if i have this html code : 
`<i class="fa fa-exclamation-triangle" aria-hidden="true"/></i> Signaler le numéro`

If i minify i lost the space after the `</i>`tag

`<i class="fa fa-exclamation-triangle" aria-hidden="true"/></i>Signaler le numéro`

Is there any way to prevent that?

**Comment by Josee9988** [comment]
Try using: `&nbsp;` as a way to replace that space.

[StackOverflow question about that 'code'](https://stackoverflow.com/questions/16951133/when-to-use-nbsp)

Try it out and let me know if the problem persists ;)

```html
<i class="fa fa-exclamation-triangle" aria-hidden="true"/></i>&nbsp;Signaler le numéro

```

**Comment by kwizfreak** [comment]
Perfect :) thanks you
