### ISSUE TITLE
Have it work in command line without `vscode`

### ISSUE THREAD

**Issue by caot** [Josee9988/MinifyAll#34]
**Is your feature request related to a problem? Please describe.**
It's good to have it work in command line without `vscode`. https://github.com/babel/minify is pretty good. Some developers like vscode, however not all of them. So command line is good to have the minified be replicated on different environments or platforms.

**Describe the solution you'd like**
`minify <directory>, the output could be such as <PATH>/<filename>.min<.js>`

**Comment by Josee9988** [comment]
Hi @caot that is definitely a thing I will do and probably in the upcoming days as I have some free time now, but thanks for posting it out because it really motivated me to do it.

For now, you can also minify your code directly from your browser: [minifyall web](https://minifyall.jgracia.es/)

**Comment by Josee9988** [comment]
Hi again @caot I have a working command already that even allows minifying a whole directory to find .html/.css/.json files recursively. it will be published as soon as I do some basic testing, write a decent readme.md and do the command tests.
So stay tuned!

**Comment by Josee9988** [comment]
Hope this solves this issue [link to the minifyall cli and package npm command](https://github.com/Josee9988/MinifyAllCli).

Hope to see your thoughts and improvements soon @caot 
Closing issue.

Thanks for your posting out!
