### ISSUE TITLE
Allow minification of unsaved temp documents, or currently selected content.

### ISSUE THREAD

**Issue by Janooba** [Josee9988/MinifyAll#5]
Is it possible to either allow minification of unsaved temp documents (File>New File -> write/paste some code without saving) or implement minification of currently selected text?

I've run into the need to do this multiple times over the last few months and no other extension even comes close to implementing it other than [Minify selection](https://github.com/Box-Of-Hats/vscode-minify-selection) which only supports CSS

**Comment by Josee9988** [comment]
@Janooba Yes, this can be done, I will check if I can make another command that only applies to selected text. 

I hope to get this thing fixed fast once I get into it in the upcoming days, as I don't have much time right now.

Thanks for commenting and letting me know how the users feel about the extension and how to enhance it.!! I'll keep you posted

**Comment by Josee9988** [comment]
Hi @Janooba in the new version 1.5.0 already available you can check the new selected text command, also you will not be forced to save the document to minify.

https://github.com/Josee9988/MinifyAll/commit/3001a2c72873c65a0b51bf4ee133e8a07a5dd953

Hope you have a great day and still help us improve!

**Comment by Janooba** [comment]
Beautiful. Thanks @Josee9988 . Your speed is highly appreciated over here!
