### ISSUE TITLE
Can't use 'Minify the selected document and preserve the original (ENOENT W10 error)'

### ISSUE THREAD

**Issue by saundersp** [Josee9988/MinifyAll#52]
**Describe the bug**
Can't use 'Minify the selected document and preserve the original :gem:', 

**To Reproduce**
1. Right click a file (Javascript in my case)
2. Select 'Minify the selected document and preserve the original :gem:'

**Expected behavior**
The minified document should be next to the original one.

**Screenshots**
![image](https://user-images.githubusercontent.com/44078749/87985634-350ece00-cadc-11ea-96a5-7c914c09f225.png)

**Additional context**
- Moving the file in the C drive (or any other drive) doesn't fix it.
- All the other commands works as expected on the tested file.

**Comment by Josee9988** [comment]
Duplicate issue #19 #17

But as it is still giving problems I will try to see if I can find that bug myself.

Thanks for posting the issue. Stay tuned for new updates.

**Comment by Zaczero** [comment]
Having the same issue :/

![200724224135_Code_6ba117](https://user-images.githubusercontent.com/10835147/88433702-dfe5fb80-cdfe-11ea-9f1c-fbd8ec53746c.png)

**Comment by Josee9988** [comment]
Seems like it is working now.

Download the latest version 2.4.2

Sorry to keep you waiting and thanks for contributing.
Let me know if the problem persists or if it is working as expected.

Thanks!!
