### ISSUE TITLE
MinifyAll.PrefixOfNewMinifiedFiles setting is ignored (prefix is always -min)

### ISSUE THREAD

**Issue by Zaczero** [Josee9988/MinifyAll#54]
**Describe the bug**
MinifyAll.PrefixOfNewMinifiedFiles setting is ignored, minified file always ends with `-min`.

**To Reproduce**
Video: [200724224651_337eb0.zip](https://github.com/Josee9988/MinifyAll/files/4974180/200724224651_337eb0.zip)

**Expected behavior**
Make it so I can set minified files with `.min` extension :-)

**Screenshots**
N/A

**Additional context**
The issue **ALSO** persists when all minified files are deleted (-min, .min etc.) and a new one must be created.

**Comment by Josee9988** [comment]
I'll check it as soon as I can.

Thanks for contributing!

**Comment by Josee9988** [comment]
Hi, I've been testing the minifier and seems like everything is fine. I **can NOT** view your video, so would you mind telling the steps to make the minifier fail or upload the video to a webpage such as Imgur?

Thanks!!!

**Comment by Zaczero** [comment]
> 
> 
> Hi, I've been testing the minifier and seems like everything is fine. I **can NOT** view your video, so would you mind telling the steps to make the minifier fail or upload the video to a webpage such as Imgur?
> 
> Thanks!!!

1. Installed the extension
2. Opened js file
3. Noticed it is not saving in correct format
4. Opened VS settings
5. Changed the setting
6. Tried to save again and still nothing

Video uses H265 encoding so that's probably the reason.
https://imgur.com/a/xcxcvfM

**Comment by Josee9988** [comment]
Hi, @Zaczero I have been testing it and seems like it is working properly for me. Try to open the *VSCode `settings.json`* file to manually review what settings you have related to MInifyAll.

Maybe there is something that is overriding that setting.

- Try for updates
- Change the setting and then restart VSCode
- Reinstall the extension.
- Make sure to install the newest MinifyAll version (released today) **2.4.1**.

If the problem still persists, make sure to contact me again through this issue.

Watch the video I just did [trying out this setting deeply](https://imgur.com/a/OX4pAXk).

Thanks!!
