### ISSUE TITLE
V2.4.7 failing

### ISSUE THREAD

**Issue by danloh** [Josee9988/MinifyAll#66]
# **🐞 Bug Report**

## **Describe the bug**

V2.4.7 Does not work at all, generate a blank file, delete everything when minify js file.

---

### **Is this a regression?**

Yes, it works well in v2.4.6

---

### **To Reproduce**

Just use it

---

### **Expected behaviour**

work like previous version

---

### **Your environment**

* OS: Ubuntu 5.4.0-47-generic x86_64   
* Node version:  14.5  
* Npm version:  6.14.7  
* Browser name and version:  Firefox80  

---

**Comment by Josee9988** [comment]
I will check it. Thanks for the issue!

**Comment by ehernandezperez** [comment]
Same problem here, but the resulting minified file is not empty, it contains the text "Undefined".

**Comment by Josee9988** [comment]
Only for js minimization right?

**Comment by ehernandezperez** [comment]
Yes, with JavaScript files and using "Minify this document and preserve the original".

**Comment by Josee9988** [comment]
I will try to fix it in a couple of hours. Thanks for your patience ❤️

**Comment by Josee9988** [comment]
Hey, update your MinifyAlll extension to **2.4.9**, and it should work again as expected. :D
