### ISSUE TITLE
Don't work any minify on save options

### ISSUE THREAD

**Issue by COD3BREAK3R** [Josee9988/MinifyAll#67]
When I active the option for minify when I save don't work in any of the options

Steps to reproduce the error:

1. Go to extension settings
2. Activate any option for minify on save
3. Press Ctrl+S
4. Don't work, don't minify the document

VS Code 1.49.2
Windows 10 1809 x64

**Comment by Josee9988** [comment]
Hi, right now I'm pretty busy. I will check it as soon as I have some time.

Sorry for the inconvenience

**Comment by Josee9988** [comment]
Hey, I have checked it out, and it works for me!

I'm currently using the last VSCode version (1.50.0)

Please, specify more information or post a video as evidence.

Thanks!

**Comment by COD3BREAK3R** [comment]
I updated to VS Code 1.50 and it works, but the problem is the setting is not applied unless the VS Code is closed and reopened.

**Comment by Josee9988** [comment]
Yes, you have to restart the VSCode to let MinfiyAll load all the new settings (which is done in the start)

:D
