### ISSUE TITLE
Option to preserve original variable names.

### ISSUE THREAD

**Issue by VoidNoire** [Josee9988/MinifyAll#70]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* I use this extension to aid in refactoring code and removing redundancies, and it works pretty well for that purpose, except for the fact that it renames variables. (As an aside, if there are other tools specifically made for this purpose, I'd definitely be interested to know about them.)

---

## **Describe the solution you'd like**

* I'd like an option that would prevent the extension from renaming variables, function names, etc.

---

## **Describe alternatives you've considered**

* I've considered using other "minifiers" and not using any at all, but they're just too convenient in helping me discover other ways to write seemingly better code. I also happen to think this one performs best out of the ones I tried, so I'd like to keep using it if possible.

---

### **Additional context**

* N/a.

**Comment by Josee9988** [comment]
The minifier renames the variables and function names to save space and make the code faster.

I am able to add this option but it should wait a little bit because I'm a bit busy with my university degree. But I can definitely do it.

Thanks for contributing

**Comment by Josee9988** [comment]
Hi again, could you provide a sample text for me to try this out.

**Comment by VoidNoire** [comment]
Ah hey. Not sure exactly what you're looking for, but assuming it's JS code that uses variables with long names, [maybe this could fit the bill](https://www.dropbox.com/s/ggkfnimxmpgyct8/VoidNoire-VoidNoire-cs50-problems-2020-x-project-20201217T181642.628626913Z.zip?dl=0&file_subpath=%2FVoidNoire-VoidNoire-cs50-problems-2020-x-project-20201217T181642.628626913Z%2Fnicoty.sbin.stock.trader.js)?

**Comment by Josee9988** [comment]
The upcoming minfiyall version should fully fix this issue.
There is a new setting called "terserMinifyOptions", which will let you specify any terser option you need. Including keeping fnames or variable names.
All the options available are listed here: https://github.com/terser/terser#minify-options

**Comment by Josee9988** [comment]
The version 2.5.0 is now available. Check it out and modify the settings. If something is wrong please tell me.

Thanks for contributing!
