### ISSUE TITLE
activation only on supported file types😉

### ISSUE THREAD

**Issue by EPIVISION** [Josee9988/MinifyAll#72]
*enhancement*

https://github.com/Josee9988/MinifyAll/blob/420dcc72ae0eedaa32a9d1388334c00e884cbc4b/package.json#L69 | activation only on supported file types (reduce vs code startup time) [see here](https://code.visualstudio.com/api/references/activation-events#onLanguage)
-|-
![drake no](https://s3.amazonaws.com/hiphopdx-production/2015/10/drake-hotline-bling-jacket-moncler.png)|![drake yes](https://i.kym-cdn.com/entries/icons/original/000/020/147/drake.jpg)

**Comment by Josee9988** [comment]
I will do that as soon as I can.
Firsts versions of MinifyAll were not activating on every file type, but due to a VSCode old error, I had to set it to *. But I'm sure it is fixed now.

Thanks!!!

**Comment by Josee9988** [comment]
MinifyAll version 2.4.10 is already published. Please check it out!
