### ISSUE TITLE
Minify on JavaScript doesn't work correctly

### ISSUE THREAD

**Issue by drodiger** [Josee9988/MinifyAll#76]
# **🐞 Bug Report**

## **Describe the bug**

If I minify following code:
```
function jsonPath(obj, expr, arg) {
    var P = {
        resultType: arg && arg.resultType || "VALUE",
        result: [],
        normalize: function (t) {
            var n = [];
            return "test"
        }
    }
}
```
this is translated on minify to:
`function jsonPath(n,t,e){e&&e.resultType}
`
Variable P is javascript JSON object, maybe it uses JSON minify, instead of JavaScript minify.
Whole file is tagged as JavaScript document, not JSON.

### **Your environment**

* OS: Win 10
VS Code: 1.52.1 (user)
MinifyAll: 2.4.13
---

**Comment by Josee9988** [comment]
Hi! Thanks for posting out! Any JavaScript issue should be added in the Terser's repository. MinifyAll uses their js minifier. The other languages are made by me, but the js minimization comes from Terser.

**Comment by drodiger** [comment]
> Hi! Thanks for posting out! Any JavaScript issue should be added in the Terser's repository. MinifyAll uses their js minifier. The other languages are made by me, but the js minimization comes from Terser.

I will check there. I see they have 134 open issues...

**Comment by Josee9988** [comment]
> > Hi! Thanks for posting out! Any JavaScript issue should be added in the Terser's repository. MinifyAll uses its js minifier. The other languages are made by me, but the js minimization comes from Terser.
> 
> I will check there. I see they have 134 open issues...

I know, if they fixed the problem you addressed, then I just have to update their package and update the minifier
