### ISSUE TITLE
Archlinux Distros and VS Code - Marketplace

### ISSUE THREAD

**Issue by grininmonkey** [Josee9988/MinifyAll#77]
For those of us using VSCode from the main ( Non AUR ) repository, VSCode is only searching OpenVSX and not VSCode marketplace... which means searching for extensions or attempting to install via typical instructions such as the ones provided for this extension currently do not work because this extension does not appear to be published to OpenVSX.

The work-around is to manually download and install from local file.

So my question or request is.... could someone publish this extension to OpenVSX?

Don't ask me why or for what reasons the main repo version of VSCode is set to not look at the Marketplace ( very annoying )... but I just spent 30 minutes trying to figure out what was going on with a couple of extensions that I had no issue finding and installing from another instance ( non Archlinux )... and ran into this discovery which appears to have been a ( kinda ) recent change.

Just thought I would look out for the next archlinux guy using VSCode installed from the main repos ;-)

Thanks!

**Comment by Josee9988** [comment]
I'll try to publish it to OpenVSX

**Comment by Josee9988** [comment]
Done, I guess
![image](https://user-images.githubusercontent.com/38838976/106511269-4f385880-64d0-11eb-9f0c-2dc7a7eba4de.png)
https://open-vsx.org/extension/Josee9988/minifyall

Tell me if it works!
Thanks!
