### ISSUE TITLE
Does MinifyAll Extension Work with SFTP

### ISSUE THREAD

**Issue by dougkozar** [Josee9988/MinifyAll#79]
I use SFTP by liximomo for file uploads to the server. When I minify a file using your extension, it saves locally but does not upload to the server. My SFTP settings are set to upload on save and works fine with all files on my local machine except newly minified files.

Does your extension interact with SFTP to auto upload to the server upon local save & minify? If so, how do I make it happen?

Thank you!

**Comment by Josee9988** [comment]
Hi, the extension does not interact at any way with SFTP, it should not be a problem at all. If you are automating the process, make sure you minify the file with the name that you are expecting and then uploading it.

**Comment by dougkozar** [comment]
I was looking to see if there was anyway for your extension to auto upload to the server on save (in addition to it saving the minified file locally). I was hoping I would not have to open the minified file in VS Code and the manually upload it.

**Comment by Josee9988** [comment]
I have a npm extension so you could fully automate it without needing to open vscode.
Here is the project https://github.com/Josee9988/MinifyAllCli

**Comment by dougkozar** [comment]
Ok, but I think the answer to posted question is "**no**", I cannot set the MinifyAll extension to auto upload a saved/minified file to the server, Correct?

**Comment by dougkozar** [comment]
I can alter my processes to manually save (so it auto uploads to the server) the newly minified file but when I do, I get another minified file. See screenshot. Just an FYI.
![Screen Shot 2021-02-22 at 1 53 52 PM](https://user-images.githubusercontent.com/14360071/108755806-b36d9b80-7515-11eb-8bff-92668d0b8a9d.png)

**Comment by Josee9988** [comment]
> Ok, but I think the answer to posted question is "**no**", I cannot set the MinifyAll extension to auto upload a saved/minified file to the server, Correct?

No, MinifyAll just minifies the code. If you want to upload it, then you will have to do so manually or automate a task.

**Comment by dougkozar** [comment]
Thanks. Is "automating tasks" something easy to learn and do within VS Code?

**Comment by Josee9988** [comment]
Not a VSCode related thing. You may do a shell script and upload the files to your server using scp
