### ISSUE TITLE
Change minified file name

### ISSUE THREAD

**Issue by giuliac1989** [Josee9988/MinifyAll#8]
Hi, it's possibile to customize the minified file name?
I would like it to be for example styles.min.css instead styles-min.css

**Comment by Josee9988** [comment]
Hi, @giuliac1989  there is no possible way to do so **now**, but I'll look forward to it by adding a setting so the user could choose.
I will try to make it ASAP, probably today or **the upcoming days**, so stay tuned and thanks for helping the extension even better!

**Comment by giuliac1989** [comment]
Thank you @Josee9988! The extension is great :)

**Comment by Josee9988** [comment]
Hey @giuliac1989 I've just created a new setting called "MinifyAll.PrefixOfNewMinifiedFiles", there you can choose upon 4 options :)
<img src="https://i.imgur.com/1yBEQYJ.png" alt="new option" title="new option" style="border-radius:15px; box-shadow: 6px 6px  #282829; max-height: 750px; max-width:750px;margin-left: auto; margin-right:auto;display: block;margin-left: auto;margin-right:auto;width:75%;"/>
Hope you help us on more occasions!
Thanks!
