### ISSUE TITLE
Unfounded message

### ISSUE THREAD

**Issue by juanyves** [Josee9988/MinifyAll#86]
I enabled minifyOnSaveToNewFile and minifyOnSave is disabled by default as I want the format on a new file.
I don't want to disable the message.
Any way thanks for that nice extension

**Comment by Josee9988** [comment]
So it does not minify your file?

What file type are you minifying (.css, .js, .html)...?

Thanks for the issue!

**Comment by Josee9988** [comment]
Hey I can't see your issue description, have you deleted it? 😄

**Comment by juanyves** [comment]
That was a mistake.
What I mean is that if a type of file is disable always comes out the advice that it will not be formatted because it's disabled. That message will always comes out without necessity. May be it can be disabled.
Previously I had the problem that it was comming out even for the js files minified on a new file but since I disabled the messages and enbled them again it doesn't come out again. But still comes out every time I save a type of file which is disabled.
Thanks.

**Comment by Josee9988** [comment]
Ow I get it, the message is shown because you have MinifyaonSave enabled. I will fix it

**Comment by Josee9988** [comment]
I think I fixed it, download the latest extension version (2.5.9) and check it out.

Thanks for contributing and consider star-ing⭐ the project if you enjoy it!🔥
