### ISSUE TITLE
New extension icon

### ISSUE THREAD

**Issue by devmahdi404** [Josee9988/MinifyAll#98]
can you upgrade the extension icon, that would be nice.

**Comment by Josee9988** [comment]
Definitely it needs an update, but as I don't earn a single $ with it I can pay a fiverr designer to make me a decent one. I'll have to do something myself which will be pretty ...

**Comment by Josee9988** [comment]
I could only do something with tools like: https://www.freelogodesign.org/
![minifyall?](https://user-images.githubusercontent.com/38838976/114359144-f4784880-9b73-11eb-84b9-fd4f3ca15b08.png)
![minifyall?2](https://user-images.githubusercontent.com/38838976/114359852-b0397800-9b74-11eb-99dc-a2969ce63f45.png)
![minifyall?3](https://user-images.githubusercontent.com/38838976/114359858-b16aa500-9b74-11eb-9292-8c916184733f.png)

And I mean neither of these logos are bad at all but they are public, so probably other company or user or whatever might have used them already.

Tell me what you think I should do 😄

**Comment by DevMahdi404** [comment]
> 
> 
> Definitely, it needs an update, but as I don't earn a single $ with the extension I can not pay a Fiverr designer to make me a decent one. I'll have to do something myself which will be pretty ... Let's say not ok

**Comment by DevMahdi404** [comment]
the second logo is quite good, you could use that. And thanks for such an amazing extension ❤️❤️

**Comment by Josee9988** [comment]
Yeah, this one is not bad at all but for the free version I only get a 200x200px file, so it is really not worth

Thanks for your support

**Comment by DevMahdi404** [comment]
the official recommendation on [Github ](https://github.com/Microsoft/vscode-docs/issues/1101)is 128x128. So, it might work well.

**Comment by Josee9988** [comment]
I'll probably post an update tomorrow so you can see how it looks an decide whether to rollback to the original or not

**Comment by Josee9988** [comment]
I updated the icon with the second one that you liked, we'll see if I keep it or rollback to the previous, meanwhile you can download the newest version and tell me how it feels :D

Thanks

**Comment by Josee9988** [comment]
![Screenshot from 2021-04-13 10-27-07](https://user-images.githubusercontent.com/38838976/114521625-e6ddc400-9c42-11eb-8d7a-23bd31f15c40.png)
![Screenshot from 2021-04-13 10-27-36](https://user-images.githubusercontent.com/38838976/114521629-e80ef100-9c42-11eb-9f3b-3a4cd872eae7.png)

It definitely needs more color!

**Comment by Josee9988** [comment]
![image](https://user-images.githubusercontent.com/38838976/114523075-412b5480-9c44-11eb-8388-fbbe5f3816ce.png)
This one is better

**Comment by DevMahdi404** [comment]
yeah, thank you for this. Hope this project gets some donation. again lot of thanks for the extension ❤️❤️

**Comment by Josee9988** [comment]
@DevMahdi404 thanks for your support!

**Comment by Josee9988** [comment]
@DigiAge has made a new one. So you can comment if you prefer the actual one or the new proposal
Actual one
![icon](https://user-images.githubusercontent.com/38838976/114768457-2b637f80-9d69-11eb-9d47-29da7b5c2d1d.png)


New one
![minifyall](https://user-images.githubusercontent.com/38838976/114768419-1be43680-9d69-11eb-9c71-9995332962fa.png)
![minifyall-backgrounds](https://user-images.githubusercontent.com/38838976/114768422-1c7ccd00-9d69-11eb-9c9a-92493c89c462.png)

**Comment by Josee9988** [comment]
I really like colour change in the word "ALL" but personally, I do prefer the original colours, I think they are more vivid, but both of them are cool

**Comment by digiage** [comment]
Current dark/light theme look in the Extensions "shop" part. Just for reference:
![image](https://user-images.githubusercontent.com/73428488/114770704-0290b980-9d6c-11eb-8dbb-87ed00d9d106.png)
![image](https://user-images.githubusercontent.com/73428488/114770714-04f31380-9d6c-11eb-918a-0ea9c7083873.png)

**Comment by Josee9988** [comment]
Maybe the logo could have a background circle-shaped around the main logo to make it stand out or something. Idk I'm not an artistic guy 😆

**Comment by DevMahdi404** [comment]
the new tweak by @digiage is good. But I think it would be better if you remove the text and fill the background circle so that the icon will be big and clear. What do you think?

**Comment by Josee9988** [comment]
Yeah, probably it will be more visible to the users

**Comment by DevMahdi404** [comment]
yeah, make a try. hopefully it will be much good.

**Comment by Josee9988** [comment]
I will close this issue as I am not focusing rn on the improvement of the icon. Thanks guys for your support!!
